### PR TITLE
Display file in browser with OSMD

### PR DESCRIPTION
**Pull request by pjcdawkins**
https://opensheetmusicdisplay.org/

### CODE REVIEW

**Comment by pjcdawkins** [comment]
Example: https://pr-13-7gt46na-gpms3vphhdy4i.eu.platform.sh/apps/score/chorales/J_S_Bach_BWV_2_6-cut2-fromATB-exercise.xml

**Comment by pjcdawkins** [comment]
@MarkGotham this doesn't look so bad anymore: https://pr-13-7gt46na-gpms3vphhdy4i.eu.platform.sh/apps/lieder/

Reflowing the score when you resize a window is... :exploding_head: 

(generate an exercise and click on the experimental "view in browser" links)

The above Bach link has some dodgy notes but I'm not sure if they are genuinely in the generated version (not having MuseScore on this machine).

**Comment by MarkGotham** [comment]
Nice!!!

With sheet music display in the browser working robustly, there are lots of other cool things we should implement.

**Comment by pjcdawkins** [comment]
I'm not sure I'd use the word "robust" but it seems good enough to be useful. Feel free to merge :)

**Pull request merged**
