### PR TITLE
Download lieder from OpenScore LiederCorpus

### PR DESCRIPTION
**Pull request by pjcdawkins**

### CODE REVIEW

**Comment by pjcdawkins** [comment]
Maybe a score issue, or maybe a music21 issue:

https://github.com/MarkGotham/When-in-Rome/blob/master/Corpus/OpenScore-LiederCorpus/Boulanger%2C_Lili/_/Dans_l%E2%80%99immense_tristesse/score.mxl

```
ERROR:root:Failed to parse score: /app/When-in-Rome/Corpus/OpenScore-LiederCorpus/Boulanger,_Lili/_/Dans_l’immense_tristesse/score.mxl
Traceback (most recent call last):
  File "/app/app/scores.py", line 82, in get_lieder_index
    score = music21.converter.parse(abspath)
  File "/app/.global/lib/python3.6/site-packages/music21/converter/__init__.py", line 1138, in parse
    forceSource=forceSource, **keywords)
  File "/app/.global/lib/python3.6/site-packages/music21/converter/__init__.py", line 1010, in parseFile
    v.parseFile(fp, number=number, format=format, forceSource=forceSource, **keywords)
  File "/app/.global/lib/python3.6/site-packages/music21/converter/__init__.py", line 551, in parseFile
    self.parseFileNoPickle(fp, number, format, forceSource, **keywords)
  File "/app/.global/lib/python3.6/site-packages/music21/converter/__init__.py", line 485, in parseFileNoPickle
    self.subConverter.parseFile(fp, number=number, **keywords)
  File "/app/.global/lib/python3.6/site-packages/music21/converter/subConverters.py", line 883, in parseFile
    c.parseXMLText()
  File "/app/.global/lib/python3.6/site-packages/music21/musicxml/xmlToM21.py", line 858, in parseXMLText
    self.xmlRootToScore(self.xmlRoot, self.stream)
  File "/app/.global/lib/python3.6/site-packages/music21/musicxml/xmlToM21.py", line 898, in xmlRootToScore
    part = self.xmlPartToPart(p, mxScorePart)
  File "/app/.global/lib/python3.6/site-packages/music21/musicxml/xmlToM21.py", line 932, in xmlPartToPart
    parser.parse()
  File "/app/.global/lib/python3.6/site-packages/music21/musicxml/xmlToM21.py", line 1472, in parse
    self.parseMeasures()
  File "/app/.global/lib/python3.6/site-packages/music21/musicxml/xmlToM21.py", line 1613, in parseMeasures
    self.xmlMeasureToMeasure(mxMeasure)
  File "/app/.global/lib/python3.6/site-packages/music21/musicxml/xmlToM21.py", line 1781, in xmlMeasureToMeasure
    self.measureParsingError(mxMeasure, e)
  File "/app/.global/lib/python3.6/site-packages/music21/musicxml/xmlToM21.py", line 1743, in measureParsingError
    raise e
  File "/app/.global/lib/python3.6/site-packages/music21/musicxml/xmlToM21.py", line 1779, in xmlMeasureToMeasure
    measureParser.parse()
  File "/app/.global/lib/python3.6/site-packages/music21/musicxml/xmlToM21.py", line 2321, in parse
    meth(mxObj)
  File "/app/.global/lib/python3.6/site-packages/music21/musicxml/xmlToM21.py", line 4491, in xmlDirection
    self.setDirectionInDirectionType(mxDir, mxDirection, staffKey, totalOffset)
  File "/app/.global/lib/python3.6/site-packages/music21/musicxml/xmlToM21.py", line 4527, in setDirectionInDirectionType
    spannerList = self.xmlDirectionTypeToSpanners(mxDir)
  File "/app/.global/lib/python3.6/site-packages/music21/musicxml/xmlToM21.py", line 3656, in xmlDirectionTypeToSpanners
    sp.endHeight = mxObj.get('end-length')
  File "/app/.global/lib/python3.6/site-packages/music21/spanner.py", line 1701, in _setEndHeight
    if not common.isNum(value) and value is not None and value >= 0:
TypeError: '>=' not supported between instances of 'str' and 'int'
```

**Comment by MarkGotham** [comment]
This is one of 5 scores failing to parse at the moment:
lc5983777, lc5995356, lc5988117, lc6166579, lc5051353
I'll investigate them.

**Comment by pjcdawkins** [comment]
OK:

https://pr-52-z7f53pa-gpms3vphhdy4i.eu.platform.sh/apps/lieder/

I have parsed the corpus with my existing [`get_score_name()`](https://github.com/fourscoreandmore/fourscoreandmore.org/blob/3dcdd453e80eef3f29d450c81506df069b69e717/cut-outs-backend/app/indexer.py#L9-L16) but it is lacking. Some standardization is going on somewhere to build your [CSV](https://github.com/MarkGotham/When-in-Rome/blob/master/Corpus/OpenScore-LiederCorpus/_OpenScore%20lieder%20corpus%20contents.csv), with values that aren't in the score metadata, e.g. some composer names are `Augusta Holmès`, some are `Holmès, Augusta`. There is a script that generates that CSV I guess? And some kind of filename convention involving underscores?

We can consider the CSV the source of truth... in which case having the filename directly there (relative to the LiederCorpus directory) would help.

**Comment by MarkGotham** [comment]
Yes, the in-score metadata is not quite consistent but the file paths are (i.e. all Holmès songs are in the Holmès folder). As such, the csv gets most of its info from the directory structure. I'm happy to commit the (very modest) script for making this csv file if that would help?

**Comment by pjcdawkins** [comment]
That makes sense. I think it's good if cut-outs uses that as the database, and that we also include the file path in the CSV rows. Note GitHub has an error on the CSV right now:

> We can make this file beautiful and searchable if this error is corrected: It looks like row 36 should actually have 8 columns, instead of 4. in line 35.

**Comment by pjcdawkins** [comment]
OK with that last commit, https://pr-52-z7f53pa-gpms3vphhdy4i.eu.platform.sh/apps/lieder/ now displays all the lieder. Well, 833 lieder, though your contents only has 829? It's searching for all "score.mxl" files.

It works well enough on desktop because of the search, but another solution is needed for mobile, probably using the split composer/collection/title data as you suggested, and/or maybe some kind of search there.

**Pull request merged**
